data:extend(
{    
        {
            type = "item",
            name = "cheetah-ore",
            icon = "__leighzercheetahore__/graphics/cheetah-ore.png",
            icon_size = 32,            
            subgroup = "raw-resource",
            order = "x-c",
            stack_size = 50,
            fuel_category = "chemical",
            fuel_value = "250KJ",
            fuel_acceleration_multiplier = 2.5,
            fuel_top_speed_multiplier = 1.15,
        },
          
        {
          type = "item",
          name = "cheetah-fuel",
          icon = "__leighzercheetahore__/graphics/cheetah-fuel.png",
          icon_size = 32,            
          subgroup = "leighzercheetahore",
          order = "zb",
          stack_size = 50,
          fuel_category = "chemical",
          fuel_value = "3MJ",
          fuel_acceleration_multiplier = 3,
          fuel_top_speed_multiplier = 1.3,
        },

        {
            type = "item",
            name = "slow-cheetah-fuel",
            icon = "__leighzercheetahore__/graphics/slow-cheetah-fuel.png",
            icon_size = 32,            
            subgroup = "leighzercheetahore",
            order = "zc",
            stack_size = 50,
            fuel_category = "chemical",
            fuel_value = "75MJ",
            fuel_acceleration_multiplier = 0.5,
            fuel_top_speed_multiplier = 0.5,
        },

        {
            type = "item",
            name = "nuclear-cheetah-fuel",
            icon = "__leighzercheetahore__/graphics/nuclear-cheetah-fuel.png",
            icon_size = 32,            
            subgroup = "leighzercheetahore",
            order = "zd",
            stack_size = 1,
            fuel_category = "chemical",
            fuel_value = "600MJ",
            fuel_acceleration_multiplier = 5,
            fuel_top_speed_multiplier = 3,
        },
})